<?php
/**
 * Конфигурация карт: регионы, цвета культур, соответствие ISO ↔ slug.
 */
return [
    'country' => [
        'center' => [41.2, 74.6],
        'zoom' => 6,
        'bounds' => [[39.0, 69.0], [43.5, 80.5]],
    ],
    'culture_colors' => [
        'wheat' => '#c9a227',
        'barley' => '#d4a574',
        'potato' => '#8b5a2b',
        'beet' => '#e11d48',
        'cotton' => '#3b82f6',
        'vegetables' => '#0d9488',
        'corn' => '#f59e0b',
        'legumes' => '#8ab17d',
        'seed' => '#4ea8de',
        'other' => '#64748b',
    ],
    'iso_to_slug' => [
        'KG-B' => 'batken',
        'KG-C' => 'chuy',
        'KG-J' => 'jalal_abad',
        'KG-N' => 'naryn',
        'KG-O' => 'osh',
        'KG-T' => 'talas',
        'KG-Y' => 'issyk_kul',
        'KGB' => 'batken',
        'KGC' => 'chuy',
        'KGJ' => 'jalal_abad',
        'KGN' => 'naryn',
        'KGO' => 'osh',
        'KGT' => 'talas',
        'KGY' => 'issyk_kul',
    ],
    'legacy_plot_redirect' => [
        'KGB' => 'batken',
        'KGC' => 'chuy',
        'KGJ' => 'jalal_abad',
        'KGN' => 'naryn',
        'KGO' => 'osh',
        'KGT' => 'talas',
        'KGY' => 'issyk_kul',
        'KGGB' => 'chuy',
    ],
    'regions' => [
        'naryn' => [
            'iso' => 'KG-N',
            'slug' => 'naryn',
            'center' => [41.428, 75.991],
            'zoom' => 10,
            'color' => '#4ea8de',
            'name_ru' => 'Нарынская область',
            'name_ky' => 'Нарын облусу',
            'name_en' => 'Naryn Region',
            'address_ru' => 'ул. Ленина, 209',
            'address_ky' => 'Ленин көч., 209',
            'address_en' => 'Lenin str., 209',
            'crops_ru' => 'Семеноводство, зерновые',
            'crops_ky' => 'Үрөнчүлүк, дан',
            'crops_en' => 'Seed production, grains',
            'extra_ru' => 'Нарынский высокогорный семеноводческий пункт.',
            'extra_ky' => 'Нарын бийик тоолуу үрөнчүлүк пункту.',
            'extra_en' => 'Naryn high-altitude seed production point.',
        ],
        'issyk_kul' => [
            'iso' => 'KG-Y',
            'slug' => 'issyk_kul',
            'center' => [42.49, 78.39],
            'zoom' => 10,
            'color' => '#1e5e3a',
            'name_ru' => 'Иссык-Кульская область',
            'name_ky' => 'Ысык-Көл облусу',
            'name_en' => 'Issyk-Kul Region',
            'address_ru' => 'г. Каракол',
            'address_ky' => 'Каракол ш.',
            'address_en' => 'Karakol city',
            'crops_ru' => 'Овощи, зерновые',
            'crops_ky' => 'Жашылчалар, дан',
            'crops_en' => 'Vegetables, grains',
            'extra_ru' => 'Иссык-Кульский высокогорный научно-опытный филиал.',
            'extra_ky' => 'Ысык-Көл бийик тоолуу илимий-тажрыйба филиалы.',
            'extra_en' => 'Issyk-Kul high-altitude scientific-experimental branch.',
        ],
        'chuy' => [
            'iso' => 'KG-C',
            'slug' => 'chuy',
            'center' => [42.87, 74.59],
            'zoom' => 10,
            'color' => '#2a9d8f',
            'name_ru' => 'Чуйская область',
            'name_ky' => 'Чүй облусу',
            'name_en' => 'Chuy Region',
            'address_ru' => 'с. Прочность, ул. Спортивная, 61',
            'address_ky' => 'Прочность айылы, Спорттук 61',
            'address_en' => 'Prochnost village, Sportivnaya 61',
            'crops_ru' => 'Сахарная свекла, зерновые',
            'crops_ky' => 'Кант кызылчасы, дан',
            'crops_en' => 'Sugar beet, grains',
            'extra_ru' => 'Опытные участки селекции пшеницы и свеклы.',
            'extra_ky' => 'Буудай жана кызылча селекциясынын тилкелери.',
            'extra_en' => 'Wheat and beet breeding experimental plots.',
        ],
        'osh' => [
            'iso' => 'KG-O',
            'slug' => 'osh',
            'center' => [40.53, 72.80],
            'zoom' => 10,
            'color' => '#e76f51',
            'name_ru' => 'Ошская область',
            'name_ky' => 'Ош облусу',
            'name_en' => 'Osh Region',
            'address_ru' => 'с. Кара-Суу, ул. Большевик',
            'address_ky' => 'Кара-Суу айылы, Большевик көч.',
            'address_en' => 'Kara-Suu village, Bolshevik str.',
            'crops_ru' => 'Зерновые культуры',
            'crops_ky' => 'Дан өсүмдүктөрү',
            'crops_en' => 'Grain crops',
            'extra_ru' => 'Кара-Сууйская опытно-селекционная станция.',
            'extra_ky' => 'Кара-Суу тажрыйба-селекциялык станциясы.',
            'extra_en' => 'Kara-Suu experimental breeding station.',
        ],
        'batken' => [
            'iso' => 'KG-B',
            'slug' => 'batken',
            'center' => [39.75, 71.00],
            'zoom' => 10,
            'color' => '#e9c46a',
            'name_ru' => 'Баткенская область',
            'name_ky' => 'Баткен облусу',
            'name_en' => 'Batken Region',
            'address_ru' => 'г. Баткен, ул. Кызыл-Кия',
            'address_ky' => 'Баткен ш., Кызыл-Кыя көч.',
            'address_en' => 'Batken city, Kyzyl-Kiya str.',
            'crops_ru' => 'Хлопок',
            'crops_ky' => 'Пахта',
            'crops_en' => 'Cotton',
            'extra_ru' => 'Селекционная станция технических культур.',
            'extra_ky' => 'Техникалык өсүмдүктөрдүн селекциялык станциясы.',
            'extra_en' => 'Industrial crops breeding station.',
        ],
        'jalal_abad' => [
            'iso' => 'KG-J',
            'slug' => 'jalal_abad',
            'center' => [41.25, 73.25],
            'zoom' => 10,
            'color' => '#f4a261',
            'name_ru' => 'Джалал-Абадская область',
            'name_ky' => 'Жалал-Абад облусу',
            'name_en' => 'Jalal-Abad Region',
            'address_ru' => 'с. Тогуз-Торо',
            'address_ky' => 'Тогуз-Торо айылы',
            'address_en' => 'Toguz-Toro village',
            'crops_ru' => 'Овощные культуры',
            'crops_ky' => 'Жашылча өсүмдүктөрү',
            'crops_en' => 'Vegetable crops',
            'extra_ru' => 'Опытный пункт садоводства и овощеводства.',
            'extra_ky' => 'Мөмө-жемиш жана жашылча өстүрүү пункту.',
            'extra_en' => 'Horticulture and vegetable experimental point.',
        ],
        'talas' => [
            'iso' => 'KG-T',
            'slug' => 'talas',
            'center' => [42.52, 72.24],
            'zoom' => 10,
            'color' => '#8ab17d',
            'name_ru' => 'Таласская область',
            'name_ky' => 'Талас облусу',
            'name_en' => 'Talas Region',
            'address_ru' => 'г. Талас',
            'address_ky' => 'Талас ш.',
            'address_en' => 'Talas city',
            'crops_ru' => 'Бобовые культуры',
            'crops_ky' => 'Буурчак өсүмдүктөрү',
            'crops_en' => 'Legumes',
            'extra_ru' => 'Филиал по селекции фасоли и гороха.',
            'extra_ky' => 'Фасоль жана буурчак селекциясы боюнча филиал.',
            'extra_en' => 'Bean and pea breeding branch.',
        ],
    ],
];
