<?php
/**
 * Участки земельного фонда Институт (4 станции на карте)
 * folder — ключ папки в KML, совпадает с data-folder на карте
 */
return [
    [
        'key' => 'ioss',
        'folder' => 'ИОСС',
        'title' => 'ГП Иссык-Кульская опытно-селекционная станция',
        'title_key' => 'station_ioss_title',
        'image' => 'assets/images/barley_field.png',
        'area' => '102,0 га',
        'area_key' => 'station_ioss_area',
        'crops' => 'Картофель, плодовые культуры, зерновые и кормовые культуры',
        'crops_key' => 'station_ioss_crops',
        'activity' => 'Семеноводство картофеля, селекционные и производственные испытания',
        'activity_key' => 'station_ioss_activity',
        'location' => 'Иссык-Кульская область, Ак-Суйский район, с. Челпек',
        'location_key' => 'station_ioss_location',
        'director' => 'Осмонов Дайырбек Турсунгазиевич',
        'director_key' => 'station_ioss_director',
        'phone' => '0709 650 412',
        'email' => '',
    ],
    [
        'key' => 'jany_pachta',
        'folder' => 'ЖАНЫ ПАХТА 482 га',
        'title' => 'ГП Семеноводческое хозяйство «Жаны-Пахта»',
        'title_key' => 'station_jany_pachta_title',
        'image' => 'assets/images/wheet1.jpg',
        'area' => '482,0 га',
        'area_key' => 'station_jany_pachta_area',
        'crops' => 'Пшеница, ячмень, люцерна и другие сельхозкультуры',
        'crops_key' => 'station_jany_pachta_crops',
        'activity' => 'Семеноводство сельхозкультур высших репродукций, земледелие',
        'activity_key' => 'station_jany_pachta_activity',
        'location' => 'Чуйская область, Сокулукский район, с. Жаны-Пахта',
        'location_key' => 'station_jany_pachta_location',
        'director' => 'Эргешов Арзымат Нурмаматович',
        'director_key' => 'station_jany_pachta_director',
        'phone' => '0705 619 915',
        'email' => '',
    ],
    [
        'key' => 'koss',
        'folder' => 'КОСС 239 га',
        'title' => 'ГП Кыргызская опытно-селекционная станция по сахарной свекле',
        'title_key' => 'station_koss_title',
        'image' => 'assets/images/svekla.png',
        'area' => '239,0 га',
        'area_key' => 'station_koss_area',
        'crops' => 'Сахарная свекла, зерновые и кормовые культуры',
        'crops_key' => 'station_koss_crops',
        'activity' => 'Первичное семеноводство, производство семян сахарной свеклы',
        'activity_key' => 'station_koss_activity',
        'location' => 'Чуйская область, Сокулукский район, с. Первомайское',
        'location_key' => 'station_koss_location',
        'director' => 'Есеналиев Кубанычбек Дженишбекович',
        'director_key' => 'station_koss_director',
        'phone' => '0553 730 335',
        'email' => '',
    ],
    [
        'key' => 'atai',
        'folder' => 'Атай',
        'title' => 'ГУ Семеноводческое хозяйство «Атай»',
        'title_key' => 'station_atai_title',
        'image' => 'assets/images/corn.jpg',
        'area' => '125,8 га',
        'area_key' => 'station_atai_area',
        'crops' => 'Кукуруза, зерновые и кормовые культуры',
        'crops_key' => 'station_atai_crops',
        'activity' => 'Семеноводческое хозяйство, производство элитных семян',
        'activity_key' => 'station_atai_activity',
        'location' => 'Жалал-Абадская область, Тогуз-Тороуский район, с. Атай',
        'location_key' => 'station_atai_location',
        'director' => 'Сакеев Жыргалбек Керимжанович',
        'director_key' => 'station_atai_director',
        'phone' => '0706 341 145',
        'email' => '',
    ],
];
